// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PapyrusCs.Database;

namespace PapyrusCs.Migrations
{
    [DbContext(typeof(PapyrusContext))]
    partial class PapyrusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PapyrusCs.Database.Checksum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Crc32");

                    b.Property<byte[]>("LevelDbKey");

                    b.HasKey("Id");

                    b.HasIndex("LevelDbKey");

                    b.ToTable("Checksums");
                });
#pragma warning restore 612, 618
        }
    }
}
